name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches:
    - master
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: postclick/drone-kaniko

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  push:
    runs-on: ubuntu-latest
    if: github.event == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Tag extraction
        run: |
          TAG=(cat Dockerfile | grep FROM | head -1 | grep -o -E ":.+" | grep -o -E "[\.0-9]+")
          mkdir -p target
          echo "$TAG" > target/TAG_NAME
      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_LOGIN }}
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "postclick/drone-kaniko"
          LATEST: "true"
